# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 735484e01b423f4ab0cc53d423ef4b9cbf480577d4737e6e15fbdea5e289d7d9f9f6b797942d8244c1fe4246edf4f14508b41e78c872ecceff6ec2627b528427

test:
  secret_key_base: b0f472b4501a721eb9a2965a1e49d70736a43938df2ae89e0f76b952214498d6c4929efd4003f143ee2bd18436abc4d2fc9df6a3bb6360ec632313eba6049e4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
